-- Snowflake Connection Test Queries
SELECT CURRENT_VERSION();
SELECT CURRENT_WAREHOUSE();
SELECT CURRENT_DATABASE();
SELECT CURRENT_SCHEMA();
SELECT CURRENT_ROLE();
SELECT CURRENT_ACCOUNT();
SELECT CURRENT_REGION();
SHOW WAREHOUSES;
SHOW DATABASES; 